/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Balazs Szeleczki (https://sketchfab.com/BalazsSzeleczki)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/starship-troopers-arachnid-hopper-2429bfa8df1949c9af070ac445151a8f
Title: Starship Troopers: Arachnid Hopper
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function HopperModel({animationNumber = 0,...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/hopper.glb')
  const { actions, names } = useAnimations(animations, group)

  const animationName = names[animationNumber]


  useEffect(() => {
    const action = actions[animationName];
    if (!action) return;
  
    action.reset().setEffectiveTimeScale(1.5).fadeIn(0.5).play();
  
    return () => action.fadeOut(0.5);
  }, [animationName]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="hopper_body_mesh_low"
                  position={[0, 140.394, -3.149]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="hopper_bug_armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.mat_HooperBug}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.mat_HooperBug_wing}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[0, 140.394, -3.149]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/hopper.glb')