/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Balazs Szeleczki (https://sketchfab.com/BalazsSzeleczki)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/starship-troopers-arachnid-warrior-8ec8c09f4ce24abdad2b9b785465b49e
Title: Starship Troopers: Arachnid Warrior
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export function WarriorModel({animationNumber = 0,...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/warrior.glb')
  const { actions, names } = useAnimations(animations, group)
  const animationName = names[animationNumber]


  useEffect(() => {
    const action = actions[animationName];
    if (!action) return;
  
    action.reset().setEffectiveTimeScale(0.8).fadeIn(0.5).play();
  
    return () => action.fadeOut(0.5);
  }, [animationName]);

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="warrior_bug_object"
                  position={[0, 133.168, -2.267]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="warrior_bug_armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.mat_WarriorBug}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name="Object_8"
                      position={[0, 133.168, -2.267]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/warrior.glb')

